import matplotlib.pyplot as plt
from random import uniform
import termcolor

repetition = 1000
a = (2**16) + 3
b = 0
m = 2**29

numbers_generated = []

def method_lcg():
    seed_number = 1
    for i in range(0, repetition):
        rn = (a * seed_number + b) % m
        numbers_generated.append(rn)
        seed_number = rn

method_lcg()
numbers_generated_2 = []
x2 = []
i2 = 0
for value in range(0, 1000):
    numbers_generated_2.append(uniform(0,1))
    i2 += 1
    x2.append(i2)

total_numbers_generated = numbers_generated + numbers_generated_2

termcolor.cprint('The 1000 numbers generated by the LCG method are:', 'cyan')
print(numbers_generated)

termcolor.cprint('===========================================', 'green')

termcolor.cprint('The 1000 numbers generated by the function uniform are:', 'cyan')
print(numbers_generated_2)

plt.hist(total_numbers_generated)
plt.title('2000 random numbers')
plt.xlabel('Numbers')
plt.ylabel('Nº of repetitions')
plt.show()
